[package]
name = "electrs-wrapper"
version = "0.1.0"
authors = ["Vivienbcr <vivien.boucher@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
tokio = { version = "0.2", features = ["full"] }
bitcoin = "0.25.0"
serde = { version = "1.0.116", features = ["derive"] }